[package]
name = "ditt_lang"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "ditt"
path = "src/main.rs"

[dependencies]
unicode-ident = "1.0"

[dev-dependencies]
proptest = "1.6.0"
regex = "1"
serde_json = "1.0"
